export const ADD_TO_CART = 'addToCart'
export const CHOOSE_ITEM = 'chooseItem'
export const UN_CHOOSE_ITEM = 'unChooseItem'
export const CHOOSE_ALL = 'chooseAll'
export const UN_CHOOSE_ALL = 'unChooseAll'
